# Generated by Django 3.2.5 on 2021-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingitem',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
    ]
