# Generated by Django 3.2.5 on 2021-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0002_alter_biddingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingitem',
            name='image',
            field=models.ImageField(default='item_images/default.jpg', upload_to='item_images'),
        ),
    ]
